let Baron = {
	"name" : "BaronGOF",
    "battletags" : ["BaronGOF-2402", "TheDebaser-21783"],
    "loaded" : null,
	"rank": [],
	"level" : null,
	"rankIcon" : null,
	"averageRankIcon" : null,
	"maxRank" : null,
	"averageRank" : null,
	"playerIcon" : "https://d1u1mce87gyfbn.cloudfront.net/game/unlocks/0x02500000000017A8.png",
	"wins" : null,
	"winrate" : null,
	"loss" : null,
	"draws" : null,
	"winrateColor" : null,
	"endorsement" : null,
	"display" : false,
	"mostPlayedKey" : null,
	"mostPlayedTime" : null,
	"mostPlayed" : null,
	"lastUpdated" : null,
	"lastUpdatedTimer" : null,
	"fetching" : false
}

let Metodios = {
	"name" : "Metodios",
	"battletags" : ["Metodios-2865", "Motodies-2516"],
	"rank": [],
    "level" : 0,
    "loaded" : null,
	"rankIcon" : null,
	"averageRankIcon" : null,
	"maxRank" : null,
	"averageRank" : null,
	"playerIcon" : null,
	"wins" : null,
	"winrate" : null,
	"loss" : null,
	"draws" : null,
	"winrateColor" : null,
	"endorsement" : null,
	"display" : false,
	"mostPlayedKey" : null,
	"mostPlayedTime" : null,
	"mostPlayed" : null,
	"lastUpdated" : null,
	"lastUpdatedTimer" : null,
	"fetching" : false
}

let Alykas = {
	"name" : "Alykas",
	"battletags" : ["Alykas-2309", "Sacha-21922", "Sacha-21159"],
	"rank": [],
	"level" : 0,
    "rankIcon" : null,
    "loaded" : null,
	"averageRankIcon" : null,
	"maxRank" : null,
	"averageRank" : null,
	"playerIcon" : null,
	"wins" : null,
	"winrate" : null,
	"loss" : null,
	"draws" : null,
	"winrateColor" : null,
	"endorsement" : null,
	"display" : false,
	"mostPlayedKey" : null,
	"mostPlayedTime" : null,
	"mostPlayed" : null,
	"lastUpdated" : null,
	"lastUpdatedTimer" : null,
	"fetching" : false
}

let Veybex = {
	"name" : "Veybex",
	"battletags" : ["Veybex-2428", "Sparks-21157"],
	"rank": [],
	"level" : 0,
    "rankIcon" : null,
    "loaded" : null,
	"averageRankIcon" : null,
	"maxRank" : null,
	"averageRank" : null,
	"playerIcon" : null,
	"wins" : null,
	"winrate" : null,
	"loss" : null,
	"draws" : null,
	"winrateColor" : null,
	"endorsement" : null,
	"display" : false,
	"mostPlayedKey" : null,
	"mostPlayedTime" : null,
	"mostPlayed" : null,
	"lastUpdated" : null,
	"lastUpdatedTimer" : null,
	"fetching" : false
}

let Aku = {
	"name" : "Aku",
	"battletags" : ["Aku-22455"],
	"rank": [],
	"level" : 0,
	"rankIcon" : null,
    "averageRankIcon" : null,
    "loaded" : null,
	"maxRank" : null,
	"averageRank" : null,
	"playerIcon" : null,
	"wins" : null,
	"winrate" : null,
	"loss" : null,
	"draws" : null,
	"winrateColor" : null,
	"endorsement" : null,
	"display" : false,
	"mostPlayedKey" : null,
	"mostPlayedTime" : null,
	"mostPlayed" : null,
	"lastUpdated" : null,
	"lastUpdatedTimer" : null,
	"fetching" : false
}

let Greenfinite = {
	"name" : "Greenfinite",
	"battletags" : ["Greenfinite-2408"],
	"level" : 0,
    "rankIcon" : null,
    "loaded" : null,
	"averageRankIcon" : null,
	"maxRank" : null,
	"averageRank" : null,
	"playerIcon" : null,
	"wins" : null,
	"winrate" : null,
	"rank": [],
	"loss" : null,
	"draws" : null,
	"winrateColor" : null,
	"endorsement" : null,
	"display" : false,
	"mostPlayedKey" : null,
	"mostPlayedTime" : null,
	"mostPlayed" : null,
	"lastUpdated" : null,
	"lastUpdatedTimer" : null,
	"fetching" : false
}

let Jadixa = {
	"name" : "Jadixa",
	"battletags" : ["Jadixa-2738"],
	"level" : 0,
    "rank": [],
    "loaded" : null,
	"rankIcon" : null,
	"averageRankIcon" : null,
	"maxRank" : null,
	"averageRank" : null,
	"playerIcon" : null,
	"wins" : null,
	"winrate" : null,
	"loss" : null,
	"draws" : null,
	"winrateColor" : null,
	"endorsement" : null,
	"display" : false,
	"mostPlayedKey" : null,
	"mostPlayedTime" : null,
	"mostPlayed" : null,
	"lastUpdated" : null,
	"lastUpdatedTimer" : null,
	"fetching" : false
}

let team = {
	"maxRank" : null,
	"maxRankPlayer" : null,
	"minRank" : null,
	"minRankPlayer" : null,
	"averageMaxRank" : null,
	"minRankIcon" : null,
	"maxRankIcon" : null,
	"averageMaxRankIcon": null
}